title: Data science and other stuffs
email: manuel.capel82@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog about data science, computer virology, served with a bit of mathematics and miscellaneous topics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mancap314.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mancap314
permalink: /:title:output_ext
highlighter: rouge

# Categories
# Liste des catégories
collections:
  category:
    output: true # generate HTML page
    permalink: /:collection/:name/index.html

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: mc-data
