title: Data science and other stuffs
email: manuel.capel82@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog about data science, computer virology, served with a bit of mathematics and miscellaneous topics
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mancap314

# Build settings
theme: minima
plugins:
- jekyll-feed

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: mc-data

